create table rss_parser_template (
    id bigint generated by default as identity primary key,
    template_code varchar(80) not null,
    template_name varchar(120) not null,
    description text,
    field_mapping jsonb not null default '{}'::jsonb,
    content_selectors jsonb not null default '[]'::jsonb,
    cover_selectors jsonb not null default '[]'::jsonb,
    time_formats jsonb not null default '[]'::jsonb,
    cleanup_rules jsonb not null default '{}'::jsonb,
    enabled boolean not null default true,
    created_at timestamp with time zone not null default now(),
    updated_at timestamp with time zone not null default now(),
    constraint uk_rss_parser_template_code unique (template_code)
);

comment on table rss_parser_template is 'RSS 解析模板表，保存不同订阅源的字段映射和清洗规则';
comment on column rss_parser_template.id is '解析模板主键';
comment on column rss_parser_template.template_code is '解析模板编码，用于程序内稳定引用';
comment on column rss_parser_template.template_name is '解析模板名称，用于界面展示';
comment on column rss_parser_template.description is '解析模板说明，记录适用来源和注意事项';
comment on column rss_parser_template.field_mapping is '标准字段映射配置，JSON 结构保存来源字段到标准字段的关系';
comment on column rss_parser_template.content_selectors is '正文候选字段或选择器列表，按优先级从高到低保存';
comment on column rss_parser_template.cover_selectors is '封面图候选字段或选择器列表，按优先级从高到低保存';
comment on column rss_parser_template.time_formats is '自定义时间格式列表，用于处理非标准发布时间';
comment on column rss_parser_template.cleanup_rules is '正文清洗规则，JSON 结构保存移除标签、属性和过滤策略';
comment on column rss_parser_template.enabled is '是否启用该解析模板';
comment on column rss_parser_template.created_at is '解析模板创建时间';
comment on column rss_parser_template.updated_at is '解析模板最后更新时间';

create table rss_feed (
    id bigint generated by default as identity primary key,
    parser_template_id bigint,
    feed_name varchar(160) not null,
    feed_url varchar(1024) not null,
    site_url varchar(1024),
    description text,
    language varchar(32),
    category varchar(80),
    icon_url varchar(1024),
    health_status varchar(32) not null default 'UNKNOWN',
    enabled boolean not null default true,
    fetch_interval_minutes integer not null default 60,
    last_fetch_at timestamp with time zone,
    next_fetch_at timestamp with time zone,
    last_success_at timestamp with time zone,
    last_failure_at timestamp with time zone,
    consecutive_failure_count integer not null default 0,
    created_at timestamp with time zone not null default now(),
    updated_at timestamp with time zone not null default now(),
    constraint uk_rss_feed_url unique (feed_url),
    constraint fk_rss_feed_parser_template foreign key (parser_template_id) references rss_parser_template (id) on delete set null,
    constraint ck_rss_feed_fetch_interval_positive check (fetch_interval_minutes > 0),
    constraint ck_rss_feed_failure_count_non_negative check (consecutive_failure_count >= 0)
);

comment on table rss_feed is 'RSS 订阅源表，保存订阅地址、抓取频率、健康状态和模板绑定关系';
comment on column rss_feed.id is '订阅源主键';
comment on column rss_feed.parser_template_id is '绑定的解析模板主键，为空时使用默认解析逻辑';
comment on column rss_feed.feed_name is '订阅源名称';
comment on column rss_feed.feed_url is 'RSS 或 Atom 订阅地址';
comment on column rss_feed.site_url is '订阅源所属网站地址';
comment on column rss_feed.description is '订阅源说明';
comment on column rss_feed.language is '订阅源语言代码';
comment on column rss_feed.category is '订阅源分类';
comment on column rss_feed.icon_url is '订阅源图标地址';
comment on column rss_feed.health_status is '订阅源健康状态，取值如 UNKNOWN、HEALTHY、WARNING、ERROR';
comment on column rss_feed.enabled is '是否启用该订阅源抓取';
comment on column rss_feed.fetch_interval_minutes is '抓取间隔分钟数';
comment on column rss_feed.last_fetch_at is '最近一次抓取开始时间';
comment on column rss_feed.next_fetch_at is '下一次计划抓取时间';
comment on column rss_feed.last_success_at is '最近一次成功抓取时间';
comment on column rss_feed.last_failure_at is '最近一次失败抓取时间';
comment on column rss_feed.consecutive_failure_count is '连续抓取失败次数';
comment on column rss_feed.created_at is '订阅源创建时间';
comment on column rss_feed.updated_at is '订阅源最后更新时间';

create index idx_rss_feed_parser_template on rss_feed (parser_template_id);
create index idx_rss_feed_enabled_next_fetch on rss_feed (enabled, next_fetch_at);
create index idx_rss_feed_health_status on rss_feed (health_status);

create table rss_article (
    id bigint generated by default as identity primary key,
    feed_id bigint not null,
    guid varchar(1024),
    article_url varchar(2048) not null,
    canonical_url varchar(2048),
    title varchar(500) not null,
    summary text,
    content_html text,
    author varchar(255),
    published_at timestamp with time zone,
    fetched_at timestamp with time zone not null default now(),
    cover_image_url varchar(2048),
    fingerprint varchar(128) not null,
    raw_payload jsonb not null default '{}'::jsonb,
    parse_trace jsonb not null default '{}'::jsonb,
    reading_minutes integer,
    word_count integer,
    created_at timestamp with time zone not null default now(),
    updated_at timestamp with time zone not null default now(),
    constraint fk_rss_article_feed foreign key (feed_id) references rss_feed (id) on delete cascade,
    constraint uk_rss_article_feed_url unique (feed_id, article_url),
    constraint uk_rss_article_feed_fingerprint unique (feed_id, fingerprint),
    constraint ck_rss_article_reading_minutes_non_negative check (reading_minutes is null or reading_minutes >= 0),
    constraint ck_rss_article_word_count_non_negative check (word_count is null or word_count >= 0)
);

comment on table rss_article is 'RSS 文章表，保存标准化后的文章内容、来源信息和去重指纹';
comment on column rss_article.id is '文章主键';
comment on column rss_article.feed_id is '文章所属订阅源主键';
comment on column rss_article.guid is 'RSS 条目的 GUID 或 Atom ID';
comment on column rss_article.article_url is '文章原始链接';
comment on column rss_article.canonical_url is '文章规范化链接';
comment on column rss_article.title is '文章标题';
comment on column rss_article.summary is '文章摘要';
comment on column rss_article.content_html is '清洗后的文章正文 HTML';
comment on column rss_article.author is '文章作者';
comment on column rss_article.published_at is '文章发布时间';
comment on column rss_article.fetched_at is '文章抓取入库时间';
comment on column rss_article.cover_image_url is '文章封面图地址';
comment on column rss_article.fingerprint is '文章去重指纹，由关键字段生成';
comment on column rss_article.raw_payload is '原始 RSS 条目数据，JSON 结构保存用于排查和重放解析';
comment on column rss_article.parse_trace is '解析命中轨迹，记录字段命中路径和模板处理结果';
comment on column rss_article.reading_minutes is '预计阅读分钟数';
comment on column rss_article.word_count is '文章字数';
comment on column rss_article.created_at is '文章记录创建时间';
comment on column rss_article.updated_at is '文章记录最后更新时间';

create unique index uk_rss_article_feed_guid on rss_article (feed_id, guid) where guid is not null;
create index idx_rss_article_feed_published_at on rss_article (feed_id, published_at desc);
create index idx_rss_article_fetched_at on rss_article (fetched_at desc);

create table rss_article_user_state (
    id bigint generated by default as identity primary key,
    article_id bigint not null,
    user_key varchar(80) not null default 'default',
    read boolean not null default false,
    favorite boolean not null default false,
    read_later boolean not null default false,
    archived boolean not null default false,
    read_at timestamp with time zone,
    favorited_at timestamp with time zone,
    read_later_at timestamp with time zone,
    archived_at timestamp with time zone,
    created_at timestamp with time zone not null default now(),
    updated_at timestamp with time zone not null default now(),
    constraint fk_rss_article_user_state_article foreign key (article_id) references rss_article (id) on delete cascade,
    constraint uk_rss_article_user_state_article_user unique (article_id, user_key)
);

comment on table rss_article_user_state is '文章用户阅读状态表，保存已读、收藏、稍后读和归档状态';
comment on column rss_article_user_state.id is '文章状态主键';
comment on column rss_article_user_state.article_id is '关联文章主键';
comment on column rss_article_user_state.user_key is '用户标识，单用户阶段默认使用 default';
comment on column rss_article_user_state.read is '是否已读';
comment on column rss_article_user_state.favorite is '是否收藏';
comment on column rss_article_user_state.read_later is '是否加入稍后读';
comment on column rss_article_user_state.archived is '是否归档';
comment on column rss_article_user_state.read_at is '标记已读时间';
comment on column rss_article_user_state.favorited_at is '标记收藏时间';
comment on column rss_article_user_state.read_later_at is '加入稍后读时间';
comment on column rss_article_user_state.archived_at is '归档时间';
comment on column rss_article_user_state.created_at is '文章状态创建时间';
comment on column rss_article_user_state.updated_at is '文章状态最后更新时间';

create index idx_rss_article_user_state_user_flags on rss_article_user_state (user_key, read, favorite, read_later, archived);

create table rss_feed_fetch_log (
    id bigint generated by default as identity primary key,
    feed_id bigint not null,
    started_at timestamp with time zone not null,
    finished_at timestamp with time zone,
    status varchar(32) not null default 'RUNNING',
    request_url varchar(2048) not null,
    http_status integer,
    fetched_count integer not null default 0,
    new_count integer not null default 0,
    duplicate_count integer not null default 0,
    failed_count integer not null default 0,
    duration_ms bigint,
    error_message text,
    error_stack text,
    raw_response_sample text,
    created_at timestamp with time zone not null default now(),
    constraint fk_rss_feed_fetch_log_feed foreign key (feed_id) references rss_feed (id) on delete cascade,
    constraint ck_rss_feed_fetch_log_fetched_count_non_negative check (fetched_count >= 0),
    constraint ck_rss_feed_fetch_log_new_count_non_negative check (new_count >= 0),
    constraint ck_rss_feed_fetch_log_duplicate_count_non_negative check (duplicate_count >= 0),
    constraint ck_rss_feed_fetch_log_failed_count_non_negative check (failed_count >= 0),
    constraint ck_rss_feed_fetch_log_duration_non_negative check (duration_ms is null or duration_ms >= 0)
);

comment on table rss_feed_fetch_log is 'RSS 抓取日志表，记录每次抓取的请求、数量统计和错误信息';
comment on column rss_feed_fetch_log.id is '抓取日志主键';
comment on column rss_feed_fetch_log.feed_id is '关联订阅源主键';
comment on column rss_feed_fetch_log.started_at is '抓取开始时间';
comment on column rss_feed_fetch_log.finished_at is '抓取结束时间';
comment on column rss_feed_fetch_log.status is '抓取状态，取值如 RUNNING、SUCCESS、FAILED、PARTIAL';
comment on column rss_feed_fetch_log.request_url is '本次抓取请求地址';
comment on column rss_feed_fetch_log.http_status is '远端响应 HTTP 状态码';
comment on column rss_feed_fetch_log.fetched_count is '本次抓取解析出的条目数量';
comment on column rss_feed_fetch_log.new_count is '本次新增入库文章数量';
comment on column rss_feed_fetch_log.duplicate_count is '本次判定为重复的文章数量';
comment on column rss_feed_fetch_log.failed_count is '本次解析或保存失败的条目数量';
comment on column rss_feed_fetch_log.duration_ms is '本次抓取耗时毫秒数';
comment on column rss_feed_fetch_log.error_message is '抓取失败时的可读错误信息';
comment on column rss_feed_fetch_log.error_stack is '抓取失败时的异常堆栈摘要';
comment on column rss_feed_fetch_log.raw_response_sample is '远端响应样本，用于排查格式异常';
comment on column rss_feed_fetch_log.created_at is '抓取日志创建时间';

create index idx_rss_feed_fetch_log_feed_started on rss_feed_fetch_log (feed_id, started_at desc);
create index idx_rss_feed_fetch_log_status on rss_feed_fetch_log (status);

create table rss_tag (
    id bigint generated by default as identity primary key,
    tag_name varchar(80) not null,
    slug varchar(100) not null,
    color varchar(32),
    description text,
    created_at timestamp with time zone not null default now(),
    updated_at timestamp with time zone not null default now(),
    constraint uk_rss_tag_name unique (tag_name),
    constraint uk_rss_tag_slug unique (slug)
);

comment on table rss_tag is '文章标签表，用于对订阅文章进行人工或规则化分类';
comment on column rss_tag.id is '标签主键';
comment on column rss_tag.tag_name is '标签名称';
comment on column rss_tag.slug is '标签 URL 友好标识';
comment on column rss_tag.color is '标签颜色，用于前端展示';
comment on column rss_tag.description is '标签说明';
comment on column rss_tag.created_at is '标签创建时间';
comment on column rss_tag.updated_at is '标签最后更新时间';

create table rss_article_tag (
    article_id bigint not null,
    tag_id bigint not null,
    created_at timestamp with time zone not null default now(),
    primary key (article_id, tag_id),
    constraint fk_rss_article_tag_article foreign key (article_id) references rss_article (id) on delete cascade,
    constraint fk_rss_article_tag_tag foreign key (tag_id) references rss_tag (id) on delete cascade
);

comment on table rss_article_tag is '文章标签关联表，保存文章和标签的多对多关系';
comment on column rss_article_tag.article_id is '关联文章主键';
comment on column rss_article_tag.tag_id is '关联标签主键';
comment on column rss_article_tag.created_at is '文章标签关联创建时间';

create index idx_rss_article_tag_tag on rss_article_tag (tag_id);
