create table system_dictionary (
    id bigint generated by default as identity primary key,
    dict_type varchar(80) not null,
    item_code varchar(80) not null,
    item_label varchar(120) not null,
    description text,
    sort_order integer not null default 100,
    enabled boolean not null default true,
    created_at timestamp with time zone not null default now(),
    updated_at timestamp with time zone not null default now(),
    constraint uk_system_dictionary_type_code unique (dict_type, item_code),
    constraint ck_system_dictionary_sort_order_non_negative check (sort_order >= 0)
);

comment on table system_dictionary is '系统字典表，保存订阅源分类等可配置选项';
comment on column system_dictionary.id is '字典项主键';
comment on column system_dictionary.dict_type is '字典类型，例如 FEED_CATEGORY 表示订阅源分类';
comment on column system_dictionary.item_code is '字典项编码，同一类型内唯一，用于保存到业务表';
comment on column system_dictionary.item_label is '字典项展示名称';
comment on column system_dictionary.description is '字典项说明';
comment on column system_dictionary.sort_order is '排序值，数值越小越靠前';
comment on column system_dictionary.enabled is '是否启用该字典项';
comment on column system_dictionary.created_at is '字典项创建时间';
comment on column system_dictionary.updated_at is '字典项最后更新时间';

create index idx_system_dictionary_type_enabled_sort on system_dictionary (dict_type, enabled, sort_order, item_label);

insert into system_dictionary (dict_type, item_code, item_label, description, sort_order, enabled)
select 'FEED_CATEGORY', category, category, '从已有订阅源分类初始化', row_number() over (order by category) * 10, true
from (
    select distinct trim(category) as category
    from rss_feed
    where category is not null and trim(category) <> ''
) categories;
